
set( C2S_INSTALL_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include/c2s )

install(
  DIRECTORY
    ${C2S_PROJECT_ROOT_DIR}/c2s-util/
  DESTINATION
    ${C2S_INSTALL_INCLUDE_DIR}/c2s-util
  FILES_MATCHING PATTERN
    "*.h"
)

install(
  DIRECTORY
    ${C2S_PROJECT_ROOT_DIR}/c2s-log/
  DESTINATION
    ${C2S_INSTALL_INCLUDE_DIR}/c2s-log
  FILES_MATCHING PATTERN
    "*.h"
)

install(
  DIRECTORY
    ${C2S_PROJECT_ROOT_DIR}/c2s-core/
  DESTINATION
    ${C2S_INSTALL_INCLUDE_DIR}/c2s-core
  FILES_MATCHING PATTERN
    "*.h"
)

install(
  DIRECTORY
    ${C2S_PROJECT_ROOT_DIR}/c2s-http/
  DESTINATION
    ${C2S_INSTALL_INCLUDE_DIR}/c2s-http
  FILES_MATCHING PATTERN
    "*.h"
)

install(
  DIRECTORY
    ${C2S_PROJECT_ROOT_DIR}/c2s-rest/
  DESTINATION
    ${C2S_INSTALL_INCLUDE_DIR}/c2s-rest
  FILES_MATCHING PATTERN
    "*.h"
)
